trigger:
- master

# Do not run against PR
pr: none

pool:
  name: Azure Pipelines
  vmImage: ubuntu-16.04

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: 'tests/**/*.csproj'

- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Build module images'

- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Push module images'
  inputs:
    action: 'Push module images'
    azureSubscriptionEndpoint: '$(ServiceConnectionId)'
    azureContainerRegistry: '$(FullAcrId)'
    fillRegistryCredential: false

- task: CopyFiles@2
  displayName: 'Copy Files to drop folder'
  inputs:
    Contents: |
     deployment.template.json
     **/module.json
     edgeSmokeTest.sh
     moduleAcrPromotion.sh
    TargetFolder: '$(System.DefaultWorkingDirectory)/drop'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/drop'
